set column_ratios 1,2,3
set show_hidden true
set wrap_scroll true
set preview_files true
#set preview_images true
map <A-f> shell fzf --preview 'bat --style=numbers --color=always --line-range :10 {}' --preview-window=up:10:wrap
#map x eval if fm.thisfile.image: fm.execute_command('bash -c "chafa --animate=on --size=$(tput cols)x$(tput lines) \'' + fm.thisfile.path + '\'; read -n 1 -s"')

